services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app/