services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: subscriptions_main_app
    ports:
      - "${DJANGO_PORT}:8000"
    entrypoint: ["/project/entrypoint.sh"]
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/project/
