services:
  postgres:
    image: postgres:latest
    container_name: subscriptions_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - subscriptions_postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  subscriptions_postgres_data:
