[project]
name = "django-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "django>=5.2",
    "django-environ>=0.12.0,<4",
    "flake8>=7.2.0",
    "psycopg2>=2.9.10",
    "django-ninja (>=1.4.1,<2.0.0)",
]