# Generated by Django 5.2 on 2025-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
