# Generated by Django 5.2 on 2025-06-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
