# Generated by Django 5.2 on 2025-06-10 16:02

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=20, verbose_name="Телефон"),
            preserve_default=False,
        ),
    ]
