# Generated by Django 5.2 on 2025-06-10 16:19

import django.core.validators
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
