# Generated by Django 5.2 on 2025-06-09 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersubscription",
            unique_together={("user", "tariff", "start_date")},
        ),
    ]
