# Generated by Django 5.2 on 2025-06-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_alter_usersubscription_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="tariff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tariff_subscription",
                to="subscription.tariff",
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
